_target_: src.models.blood_cells_module.BloodCellsLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: torchvision.models.resnet50
  pretrained: True
