# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  name: "train-mps-${now:%Y-%m-%d}_${now:%H-%M-%S}"
  save_dir: "${paths.output_dir}"
  offline: False
  id: null
  anonymous: null
  project: "cell-classification"
  log_model: False
  prefix: ""
  entity: "bussolacompass"
  group: ""
  tags: []
  job_type: ""
