# @package _global_

defaults:
  - _self_
  - datamodule: blood_cells.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: blood_cells.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
